# clusterPath is the path to the task data definition file
clusterPath: /dropbox/17-18/573/Data/Documents/devtest/GuidedSumm10_test_topics.xml
# Paths to directories containing documents
documentCollections:
  aquaint: /dropbox/17-18/573/AQUAINT/
  aquaint2: /dropbox/17-18/573/AQUAINT-2/

word_limit: 100
strategy:
  name: lexrank
  embedder:
    name: tfidf
