# clusterPath is the path to the task data definition file
clusterPath: /dropbox/17-18/573/Data/Documents/evaltest/GuidedSumm11_test_topics.xml
# Paths to directories containing documents
documentCollections:
  aquaint: /dropbox/17-18/573/AQUAINT/
  aquaint2: /dropbox/17-18/573/AQUAINT-2/
  gw: /dropbox/17-18/573/ENG-GW/
word_limit: 100
strategy:
  name: lexrank
  embedder:
    name: tfidf
  redundancy_tuner: 0.6
